services:
  minio:
    image: quay.io/minio/aistor/minio:latest
    container_name: minio
    ports:
      - "9000:9000" # S3 API endpoint
      - "9001:9001" # MinIO Console (web UI)
    environment:
      MINIO_CONFIG_ENV_FILE: "/mnt/minio/config"
      MINIO_ROOT_USER: ${MINIO_USER} # Replace with a strong username
      MINIO_ROOT_PASSWORD: ${MINIO_PASSWORD} # Replace with a strong password (min 8 chars)
    volumes:
      - ./:/mnt/minio # Mount a local directory to store MinIO data√ü
    command: minio server
    networks:
      - homeLab

networks:
  homeLab:
    external: true
